const FULL_CIRCLE = Math.PI * 2;
const SIXTY_DEGREES = Math.PI / 3;
const NINETY_DEGREES = Math.PI / 2;
const FORTY_FIVE_DEGREES = Math.PI / 4;
const TWO_HUNDRED_SEVENTY_DEGREES = (Math.PI * 3) / 2;
export { FULL_CIRCLE, SIXTY_DEGREES, NINETY_DEGREES, FORTY_FIVE_DEGREES, TWO_HUNDRED_SEVENTY_DEGREES };
