
export enum Settings {
	HORIZON_LINE_RATIO = 0.65,
	FRAME_HEIGHT = -200,
	MAX_BRIGHTNESS = 60,
	PLAYER_TURN_RADIUS = 0.5,
	HUD_ON = 1,
	WALL_HEIGHT = 7,
	PLAYER_SPEED = 0.5,
	CAMERA_HEIGHT = 5,
	FRAMES_PER_SECOND = 60,
	FIELD_OF_VISION = Math.PI / 3,
	MAX_DISTANCE = 100,
	MAX_PERCENT_BRIGHTNESS = 60,
	MIN_PERCENT_BRIGHTNESS = 30,
	FADE_DISTANCE = 2,
	CANVAS_WIDTH = 400,
	HORIZON_Y = 200,
	CANVAS_HEIGHT = 640,
	RESOLUTION = 400, //TODO: fix game implementation so that display isn't squashed when this is smaller than CANVAS_WIDTH
}
