
export enum Settings {
	HORIZON_HEIGHT = 480,
	FRAME_HEIGHT = -200,
	FRAMES_PER_SECOND = 60,
	DEGREES_OF_VISION = 64,
	MAX_DISTANCE = 1000,
	MAX_PERCENT_BRIGHTNESS = 60,
	MIN_PERCENT_BRIGHTNESS = 30,
	FADE_DISTANCE = 2,
	CANVAS_WIDTH = 400,
	CANVAS_HEIGHT = 640,
	RESOLUTION = 400,
}
